# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2831a4f6af119c39a8ed5cfb7cf3a8ce8deff1c35f087e544a5a9a715c31257cf119d7ca3f6731c5ea3b9d51761da4fa476f7c235b8b25ab7a20f82c7593b691

test:
  secret_key_base: 3d0d7de4bc8348089a13b66a76f504bce4abc1dd436109843b0ebba9727cad76c78b0cd16a8a80d6e53e2b39085ca31fb600db04ab3ed0a4c21e223961ff74a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
